-- Suppression des données

PROMPT = "Suppression des tables";

DROP TABLE IF EXISTS BIEN CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ESPACE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PROPRIO CASCADE CONSTRAINTS;


-- Création des relations

PROMPT = "Création des relations";

CREATE TABLE PROPRIO(
    -- Attributes
    IdP NUMBER(6,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nom VARCHAR2(20) NOT NULL,
    Prenom VARCHAR2(15) NOT NULL,
    -- Constraints
    CONSTRAINT pk_Proprio PRIMARY KEY (IdP),
    CONSTRAINT uk_Proprio UNIQUE (Nom, Prenom)
);

CREATE TABLE ESPACE (
    -- Attributes
    IdE NUMBER(6, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Designation VARCHAR2(20) NOT NULL,
    Superficie NUMBER(6, 2) NOT NULL,
    IdERattach NUMBER(6, 0),
    -- Constraints
    CONSTRAINT pk_Espace PRIMARY KEY (IdE),
    CONSTRAINT fk_IdERattach FOREIGN KEY (IdERattach) REFERENCES ESPACE(IdE)
);

CREATE TABLE BIEN(
    -- Attributes
    IdEBien NUMBER(6,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Categorie VARCHAR2(15) NOT NULL,
    Type VARCHAR2(15) NOT NULL,
    IdP NUMBER(6,0) NOT NULL,
    Ville VARCHAR2(30) NOT NULL,
    Prix NUMBER(9, 2) NOT NULL,
    -- Constraints
    CONSTRAINT ch_Categorie CHECK (Categorie IN ('Appartement', 'Maison de campagne', 'Maison de ville', 'Villa')),
    CONSTRAINT ch_Type CHECK (Type IN ('Studio', 'T2', 'T3', 'T4', 'T5', 'T6 et plus')),
    CONSTRAINT pk_Bien_primaire PRIMARY KEY (IdEBien),
    CONSTRAINT fk_Proprio FOREIGN KEY (IdP) REFERENCES PROPRIO(IdP),
    CONSTRAINT fk_Bien_secondaire FOREIGN KEY (IdEBien) REFERENCES ESPACE(IdE)
);